### PR TITLE
Link to `dotAll` proposal

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by DmitrySoshnikov** [comment]
Thanks, sounds good.

**Comment by DmitrySoshnikov** [comment]
FWIW, probably also worth adding a link from the implementations section on the proposal page.

**Comment by mathiasbynens** [comment]
@DmitrySoshnikov Care to submit a PR? :)

**Comment by DmitrySoshnikov** [comment]
@mathiasbynens, yeah, will do a bit later.

**Pull request merged**
